//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RpsTournament.WpfApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RpsTournament.WpfApp.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your move.
        /// </summary>
        public static string ChooseMoveHeading {
            get {
                return ResourceManager.GetString("ChooseMoveHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        public static string ColumnComputerHeader {
            get {
                return ResourceManager.GetString("ColumnComputerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string ColumnNumberHeader {
            get {
                return ResourceManager.GetString("ColumnNumberHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string ColumnPlayerHeader {
            get {
                return ResourceManager.GetString("ColumnPlayerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string ColumnResultHeader {
            get {
                return ResourceManager.GetString("ColumnResultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        public static string ComputerLabel {
            get {
                return ResourceManager.GetString("ComputerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer won!.
        /// </summary>
        public static string ComputerWon {
            get {
                return ResourceManager.GetString("ComputerWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string DefaultPlayerName {
            get {
                return ResourceManager.GetString("DefaultPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw!.
        /// </summary>
        public static string Draw {
            get {
                return ResourceManager.GetString("Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tournament ended in a draw!.
        /// </summary>
        public static string DrawTournament {
            get {
                return ResourceManager.GetString("DrawTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must be 2–30 characters long..
        /// </summary>
        public static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⟳ New Tournament.
        /// </summary>
        public static string NewTournamentButtonText {
            get {
                return ResourceManager.GetString("NewTournamentButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper.
        /// </summary>
        public static string PaperButtonText {
            get {
                return ResourceManager.GetString("PaperButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶ Play.
        /// </summary>
        public static string PlayButtonText {
            get {
                return ResourceManager.GetString("PlayButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player name.
        /// </summary>
        public static string PlayerNameLabel {
            get {
                return ResourceManager.GetString("PlayerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player won!.
        /// </summary>
        public static string PlayerWon {
            get {
                return ResourceManager.GetString("PlayerWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock.
        /// </summary>
        public static string RockButtonText {
            get {
                return ResourceManager.GetString("RockButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scissors.
        /// </summary>
        public static string ScissorsButtonText {
            get {
                return ResourceManager.GetString("ScissorsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : {1}.
        /// </summary>
        public static string ScoreFormat {
            get {
                return ResourceManager.GetString("ScoreFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string ScoreLabel {
            get {
                return ResourceManager.GetString("ScoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a move..
        /// </summary>
        public static string SelectMove {
            get {
                return ResourceManager.GetString("SelectMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusLabel {
            get {
                return ResourceManager.GetString("StatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tournament has finished..
        /// </summary>
        public static string TournamentFinished {
            get {
                return ResourceManager.GetString("TournamentFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament History.
        /// </summary>
        public static string TournamentHistoryLabel {
            get {
                return ResourceManager.GetString("TournamentHistoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock Paper Scissors.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
